name: "stock_forecast_dbt"
version: "1.0.0"
config-version: 2

profile: "stock_forecast_dbt"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  stock_forecast_dbt:
    materialized: table
    bronze:
      +materialized: view
    silver:
      +materialized: view
    gold:
      +materialized: table
